package main

import "go-example/src/example"

// go run 001-hello-world.go 开发期间编译运行
// go build -o hello 001-hello-world.go  生产构建产物,指定产物名字为hello
func main() {

	// example.Hello()
	// example.Values()
	// example.Variables()
	// example.Constants()
	// example.For()
	// example.IfElse()
	// example.Switch()
	// example.Arrays()
	// example.Slice()
	// example.Map()
	// example.Range()
	// example.Function()
	// example.MultReturn()
	// example.Closure()
	// example.Pointer()
	// example.String()
	// example.Struct()
	// example.Method()
	// example.Interface()
	// example.Embed()
	// example.Generic()
	// example.Errors()
	// example.Goroutine()
	// example.Channel()
	// example.ChannelBuf()
	// example.ChannelSync()
	// example.ChannelDirect()
	// example.Select()
	// example.Timeout()
	// example.NonBlocking()
	// example.CloseChannel()
	// example.TimerExample()
	// example.Ticker()
	// example.Worker()
	// example.WaitGroup()
	// example.RateLimiting()
	// example.Atomic()
	// example.Mutex()
	// example.Sort()
	// example.Panic()
	// example.Defer()
	// example.Recover()
	// example.Strings()
	// example.Format()
	// example.Json()
	// example.Time()
	// example.Epoch()
	// example.TimeFormat()
	// example.Rand()
	// example.UrlParse()
	// example.Sha256()
	// example.Base64()
	// example.ReadFile()
	example.FilePath()
}
